# Goal
string transition   # init, stand_up, lower
---
# Result
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages
---
# Feedback
float64 status